export type IconGroup = 'mdi' | 'lucide' | 'material' | 'si'

export const ICON_GROUPS: { key: IconGroup; label: string }[] = [
  { key: 'mdi', label: 'MDI' },
  { key: 'lucide', label: 'Lucide' },
  { key: 'material', label: 'Material' },
  { key: 'si', label: 'Brands' },
]

export const siIcons: string[] = [
  // Socials & Chat
  'simple-icons:discord',
  'simple-icons:telegram',
  'simple-icons:whatsapp',
  'simple-icons:slack',
  'simple-icons:facebook',
  'simple-icons:facebookmessenger',
  'simple-icons:instagram',
  'simple-icons:tiktok',
  'simple-icons:reddit',
  'simple-icons:linkedin',
  'simple-icons:twitter',
  'simple-icons:skype',
  'simple-icons:zoom',
  'simple-icons:microsoftteams',
  'simple-icons:pinterest',
  // Media & Streaming
  'simple-icons:spotify',
  'simple-icons:youtube',
  'simple-icons:twitch',
  'simple-icons:netflix',
  'simple-icons:soundcloud',
  'simple-icons:deezer',
  'simple-icons:tidal',
  'simple-icons:vlcmediaplayer',
  'simple-icons:plex',
  'simple-icons:itunes',
  // Gaming
  'simple-icons:steam',
  'simple-icons:epicgames',
  'simple-icons:ubisoft',
  'simple-icons:riotgames',
  'simple-icons:rockstargames',
  'simple-icons:roblox',
  'simple-icons:minecraft',
  'simple-icons:playstation',
  'simple-icons:xbox',
  'simple-icons:nintendo',
  // Browsers
  'simple-icons:googlechrome',
  'simple-icons:firefox',
  'simple-icons:opera',
  'simple-icons:brave',
  'simple-icons:microsoftedge',
  'simple-icons:safari',
  // OS & Hardware
  'simple-icons:windows',
  'simple-icons:apple',
  'simple-icons:linux',
  'simple-icons:android',
  'simple-icons:nvidia',
  'simple-icons:amd',
  'simple-icons:intel',
  // Dev & DB
  'simple-icons:github',
  'simple-icons:gitlab',
  'simple-icons:visualstudiocode',
  'simple-icons:codepen',
  'simple-icons:docker',
  'simple-icons:postman',
  'simple-icons:stackoverflow',
  'simple-icons:githubcopilot',
  'simple-icons:openai',
  'simple-icons:google',
  // Design & Productivity
  'simple-icons:figma',
  'simple-icons:notion',
  'simple-icons:trello',
  'simple-icons:asana',
  'simple-icons:evernote',
  'simple-icons:todoist',
  'simple-icons:obsstudio',
  'simple-icons:blender',
  'simple-icons:unity',
  'simple-icons:unrealengine',
  // Office & Cloud
  'simple-icons:microsoftoffice',
  'simple-icons:microsoftexcel',
  'simple-icons:microsoftword',
  'simple-icons:microsoftpowerpoint',
  'simple-icons:googledrive',
  'simple-icons:dropbox',
  'simple-icons:onedrive',
  'simple-icons:adobe',
  'simple-icons:adobephotoshop',
  'simple-icons:adobeillustrator',
  'simple-icons:adobepremierepro',
  'simple-icons:adobeaftereffects',
]

export const mdiIcons: string[] = [
  // Media controls
  'mdi:play',
  'mdi:pause',
  'mdi:stop',
  'mdi:skip-next',
  'mdi:skip-previous',
  'mdi:rewind',
  'mdi:fast-forward',
  'mdi:volume-minus',
  'mdi:volume-plus',
  'mdi:volume-mute',
  'mdi:music-note',
  'mdi:headphones',
  // System controls
  'mdi:power',
  'mdi:restart',
  'mdi:lock',
  'mdi:logout',
  'mdi:login',
  'mdi:shield-lock',
  // Navigation
  'mdi:arrow-left',
  'mdi:arrow-right',
  'mdi:arrow-up',
  'mdi:arrow-down',
  'mdi:home',
  'mdi:chevron-left',
  'mdi:chevron-right',
  'mdi:chevron-up',
  'mdi:chevron-down',
  // Actions
  'mdi:magnify',
  'mdi:close',
  'mdi:check',
  'mdi:plus',
  'mdi:minus',
  'mdi:star',
  'mdi:heart',
  'mdi:bookmark',
  'mdi:delete',
  'mdi:pencil',
  'mdi:content-copy',
  'mdi:content-paste',
  'mdi:undo',
  'mdi:redo',
  'mdi:refresh',
  'mdi:sync',
  'mdi:download',
  'mdi:upload',
  'mdi:fullscreen',
  'mdi:fullscreen-exit',
  // Communication
  'mdi:email',
  'mdi:phone',
  'mdi:message',
  'mdi:bell',
  'mdi:bell-off',
  // Devices
  'mdi:monitor',
  'mdi:laptop',
  'mdi:tablet',
  'mdi:cellphone',
  'mdi:printer',
  'mdi:keyboard',
  'mdi:mouse',
  'mdi:gamepad-variant',
  'mdi:camera',
  'mdi:microphone',
  'mdi:microphone-off',
  'mdi:video',
  'mdi:video-off',
  // Connectivity
  'mdi:wifi',
  'mdi:bluetooth',
  'mdi:lan-connect',
  // Apps & tools
  'mdi:cog',
  'mdi:wrench',
  'mdi:palette',
  'mdi:calculator',
  'mdi:calendar',
  'mdi:clock',
  'mdi:alarm',
  'mdi:timer',
  'mdi:brightness-5',
  'mdi:brightness-7',
  'mdi:web',
  'mdi:google-chrome',
  'mdi:firefox',
  'mdi:microsoft-edge',
  'mdi:microsoft-windows',
  'mdi:apple',
  'mdi:linux',
  'mdi:android',
  'mdi:folder-open',
  'mdi:xml',
  'mdi:git',
  'mdi:github',
  'mdi:terminal',
  'mdi:monitor-screenshot',
  'mdi:eye',
  'mdi:eye-off',
  // Misc
  'mdi:lightbulb',
  'mdi:flash',
  'mdi:fire',
  'mdi:cloud',
  'mdi:weather-sunny',
  'mdi:weather-night',
]

export const lucideIcons: string[] = [
  // Media controls
  'lucide:play',
  'lucide:pause',
  'lucide:stop-circle',
  'lucide:skip-forward',
  'lucide:skip-back',
  'lucide:music',
  'lucide:headphones',
  'lucide:radio',
  'lucide:mic',
  'lucide:mic-off',
  'lucide:video',
  'lucide:video-off',
  // Navigation
  'lucide:home',
  'lucide:arrow-left',
  'lucide:arrow-right',
  'lucide:arrow-up',
  'lucide:arrow-down',
  'lucide:chevron-left',
  'lucide:chevron-right',
  'lucide:chevron-up',
  'lucide:chevron-down',
  // Actions
  'lucide:search',
  'lucide:x',
  'lucide:check',
  'lucide:plus',
  'lucide:minus',
  'lucide:star',
  'lucide:heart',
  'lucide:heart-crack',
  'lucide:bookmark',
  'lucide:trash-2',
  'lucide:pencil',
  'lucide:copy',
  'lucide:clipboard-paste',
  'lucide:undo',
  'lucide:redo',
  'lucide:refresh-cw',
  'lucide:download',
  'lucide:upload',
  'lucide:maximize',
  'lucide:minimize',
  'lucide:fullscreen',
  // System
  'lucide:settings',
  'lucide:lock',
  'lucide:unlock',
  'lucide:shield',
  'lucide:shield-alert',
  'lucide:key',
  'lucide:power',
  'lucide:power-off',
  'lucide:rotate-ccw',
  // Communication
  'lucide:mail',
  'lucide:phone',
  'lucide:phone-call',
  'lucide:message-square',
  'lucide:bell',
  'lucide:bell-off',
  // Devices
  'lucide:monitor',
  'lucide:laptop',
  'lucide:tablet',
  'lucide:smartphone',
  'lucide:printer',
  'lucide:keyboard',
  'lucide:mouse',
  'lucide:gamepad-2',
  'lucide:camera',
  // Connectivity
  'lucide:wifi',
  'lucide:bluetooth',
  // Apps & tools
  'lucide:chrome',
  'lucide:globe',
  'lucide:folder',
  'lucide:folder-open',
  'lucide:file',
  'lucide:file-text',
  'lucide:image',
  'lucide:link',
  'lucide:link-2',
  'lucide:terminal',
  'lucide:code-2',
  'lucide:calculator',
  'lucide:calendar',
  'lucide:clock',
  'lucide:alarm-clock',
  'lucide:palette',
  'lucide:eye',
  'lucide:eye-off',
  'lucide:save',
  // Misc
  'lucide:cloud',
  'lucide:sun',
  'lucide:moon',
  'lucide:zap',
  'lucide:flame',
  'lucide:lightbulb',
  'lucide:info',
  'lucide:alert-triangle',
  'lucide:external-link',
]

export const materialIcons: string[] = [
  // Media controls
  'material-symbols:play-arrow',
  'material-symbols:pause',
  'material-symbols:stop',
  'material-symbols:skip-next',
  'material-symbols:skip-previous',
  'material-symbols:fast-forward',
  'material-symbols:fast-rewind',
  'material-symbols:volume-up',
  'material-symbols:volume-down',
  'material-symbols:volume-off',
  'material-symbols:music-note',
  'material-symbols:headset',
  'material-symbols:mic',
  'material-symbols:mic-off',
  'material-symbols:videocam',
  'material-symbols:videocam-off',
  // Navigation
  'material-symbols:home',
  'material-symbols:arrow-back',
  'material-symbols:arrow-forward',
  'material-symbols:arrow-upward',
  'material-symbols:arrow-downward',
  'material-symbols:chevron-left',
  'material-symbols:chevron-right',
  'material-symbols:expand-less',
  'material-symbols:expand-more',
  'material-symbols:menu',
  'material-symbols:more-horiz',
  'material-symbols:more-vert',
  // Actions
  'material-symbols:search',
  'material-symbols:close',
  'material-symbols:check',
  'material-symbols:add',
  'material-symbols:delete',
  'material-symbols:edit',
  'material-symbols:star',
  'material-symbols:favorite',
  'material-symbols:bookmark',
  'material-symbols:content-copy',
  'material-symbols:content-paste',
  'material-symbols:undo',
  'material-symbols:redo',
  'material-symbols:sync',
  'material-symbols:refresh',
  'material-symbols:download',
  'material-symbols:upload',
  'material-symbols:fullscreen',
  'material-symbols:fullscreen-exit',
  // System
  'material-symbols:settings',
  'material-symbols:lock',
  'material-symbols:key',
  'material-symbols:shield',
  'material-symbols:power-settings-new',
  'material-symbols:restart-alt',
  'material-symbols:settings-backup-restore',
  // Communication
  'material-symbols:mail',
  'material-symbols:phone',
  'material-symbols:chat',
  'material-symbols:notifications',
  'material-symbols:notifications-off',
  // Devices
  'material-symbols:desktop-windows',
  'material-symbols:laptop',
  'material-symbols:tablet',
  'material-symbols:smartphone',
  'material-symbols:print',
  'material-symbols:keyboard',
  'material-symbols:mouse',
  'material-symbols:sports-esports',
  'material-symbols:camera-alt',
  // Connectivity
  'material-symbols:wifi',
  'material-symbols:bluetooth',
  // Apps & tools
  'material-symbols:public',
  'material-symbols:language',
  'material-symbols:folder-open',
  'material-symbols:description',
  'material-symbols:image',
  'material-symbols:link',
  'material-symbols:code',
  'material-symbols:terminal',
  'material-symbols:calculate',
  'material-symbols:calendar-today',
  'material-symbols:schedule',
  'material-symbols:alarm',
  'material-symbols:timer',
  'material-symbols:palette',
  'material-symbols:visibility',
  'material-symbols:visibility-off',
  'material-symbols:open-in-new',
  // Misc
  'material-symbols:cloud',
  'material-symbols:brightness-high',
  'material-symbols:dark-mode',
  'material-symbols:bolt',
  'material-symbols:local-fire-department',
  'material-symbols:lightbulb',
  'material-symbols:info',
  'material-symbols:warning',
]
